@WORDWRAP@@menu:../banner*@@TRUNCATE@
nhclient nwconn: h@CONN@
nh       nwaddr: h@HOST@ [@IP@]
nh       nwterm: h@COLS@x@ROWS@ @CHARSET@ / @TERM@
nhserver nwname: hk@WORDWRAP@0
nh       nwaddr: h@WORDWRAP@1
nh       nwnode: h@WORDWRAP@2 nw(of h@TNODE@nw) - h@WORDWRAP@4 @OS_CPU@
nh       nwtime: h@DATETIMEZONE@
nh       nwadmn: h@SYSOP@

wif you are a new user to the system, type w"new"w now.
otherwise, enter your user name or number now.
