@WORDWRAP@@MENU:../banner*@@TRUNCATE@
nhclient nwconn: h@CONN@
nh       nwaddr: h@HOST@ [@IP@]
nh       nwterm: h@COLS@x@ROWS@ @CHARSET@ / @TERM@
nhserver nwname: hk@BBS@
nh       nwaddr: h@HOSTNAME@
nh       nwnode: h@WORDWRAP@3 nw(of h@WORDWRAP@4nw) - h@OS_VER@ @OS_CPU@
nh       nwtime: h@WORDWRAP@7
nh       nwadmn: h@SYSOP@

wif you are a new user to the system, type w"new"w now.
otherwise, enter your user name or number now.
