@CLEAR@@WORDWRAP@
nhinternet e-mail:
nwyour internet e-mail address here on h@BBS@nw is:
<h@EMAILADDR@nw>

if your sysop (@SYSOP@) has enabled the synchronet mail (smtp)
server, you may be able to send and receive internet e-mail using this address,
so you may want to make a note of it.

nhsystem policies:
nwmaximum inactivity before user account deletion: h@AUTODEL@ days
nwmaximum interval of user password modifications: h@PWDAYS@ days
