@CLS@nhwthis bbs is running...
@WORDWRAP@
y .|'''.|                        '||                                      .   
y ||..  ' .... ..... ...    ....  || ..  ... ..   ...   .. ...    ....  .||.  
y  ''|||.  '|.  |  ||  || .|   '' ||' ||  ||' ''.|  '|.  ||  || .|...||  ||   
y.     '||  '|.|   ||  || ||      ||  ||  ||    ||   ||  ||  || ||       ||   
y|'....|'    '|   .||. ||. '|...'.||. ||..||.    '|..|' .||. ||. '|...'  '|.' 
y         .. |
y          ''
w              synchronet bbs for @PLATFORM@ - version @FULL_VER@
w              @COPYRIGHT@ - http://www.synchro.net
wh
native multi-threaded bulletin board system software for the internet age
nw
integrated tcp/ip servers: honw telnet/rlogin/ssh
                           honw smtp/pop3 (inbound and outbound e-mail)
                           honw ftp (with dynamic index files)
                           honw network news transfer protocol (e.g. usenet)
                           honw web (http with server-side javascript and cgi)
                           honw finger, gopher, and irc
h
native versions for windows and unix-like (e.g. linux and freebsd) platforms
n@CLS@--------------------------------------------------------------------------
hremembering these keys will help you enjoy your wsynchronetw bbs experience:
n--------------------------------------------------------------------------
w
at hk[hit a key]n prompts, you can hit hctrl-cn or 'hqn' to stop listing text.

hitting hdown arrown (or ctrl-j) at auto-hkpausen prompts will scroll one line at a
time, while hitting any other key will continue one page at a time.

the global khabortn-operation key sequence is: hctrl-cn.

other global control-key sequences include: hctrl-uy: list users onlinen
					    hctrl-py: send a private messagen
                                            hctrl-ty: show time informationn
                                            hctrl-oy: toggle auto-pause off/onn

use 'h?n' to display help menus, and use 'hqn' to quit.
