@CLS@nhwthis is y@BBS@w located in y@LOCATION@w
with your sysop, y@SYSOP@w here to serve you.

y@HOSTNAME@w is running y@OS_VER@w
and has been online continuously for y@UPTIME@w hours.

ysystem totals:w

users:     k@TUSER|L.......@w today: k@STATS.NUSERS@w
logons:    k@STATS.LOGONS|L@w today: k@STATS.LTODAY@w
timeused:  k@STATS.TIMEON|L@w today: k@STATS.TTODAY@w
messages:  k@TMSG|L........@w today: k@STATS.PTODAY@w
e-mail:    k@MAILW:0|L.....@w today: k@STATS.ETODAY@w
feedback:  k@MAILW:1|L.....@w today: k@STATS.FTODAY@w
files:     k@TFILE|L.......@w today: k@STATS.ULS@w
                 downloaded today: k@STATS.DLS@w (k@STATS.DLB@w nbytesh)
