@CLS@nhwthis is y@BBS@w located in y@LOCATION@w
with your sysop, y@SYSOP@w here to serve you.

y@HOSTNAME@w is running y@OS_VER@w
and has been online continuously for y@UPTIME@w hours.

ysystem totals:w

users:     k@TUSER|L.......@w today: k@STATS.NUSERS@w
logons:    k@STATS.LOGONS|L@w today: k@CLS@1w
timeused:  k@CLS@2w today: k@CLS@3w
messages:  k@CLS@4w today: k@CLS@5w
e-mail:    k@CLS@6w today: k@CLS@7w
feedback:  k@CLS@8w today: k@CLS@9w
files:     k@BBS@0w today: k@STATS.ULS@w
                 downloaded today: k@STATS.DLS@w (k@STATS.DLB@w nbytesh)
