@CLS@nhwthis is y@BBS@w located in y@LOCATION@w
with your sysop, y@SYSOP@w here to serve you.

y@HOSTNAME@w is running y@OS_VER@w
and has been online continuously for y@UPTIME@w hours.

ysystem totals:w

users:     k@tuser|l.......@w today: k@STATS.NUSERS@w
logons:    k@stats.logons|l@w today: k@STATS.LTODAY@w
timeused:  k@stats.timeon|l@w today: k@CLS@0w
messages:  k@tmsg|l........@w today: k@CLS@1w
e-mail:    k@mailw:0|l.....@w today: k@CLS@2w
feedback:  k@mailw:1|l.....@w today: k@CLS@3w
files:     k@tfile|l.......@w today: k@CLS@4w
                 downloaded today: k@CLS@5w (k@CLS@6w nbytesh)
