NHK@HOT@N@CLEAR@
0WÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄK¿
W³ HKbatch file transfer menu N0K³
WÀKÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ0WÜÜÜÜÜÜÜÜÜÜÜ
Ûß„ß0 HWupload/downloadNWÛH0WfilesNWÛß„ßÛ
Û HKu NWuploadH NWfiles in upload queueW…WÛ
Û HKd NWdownload files in download queueW  WÛ
Û²ÄÄÄÄß0 HWbatch queue managementNWÛßÄÄÄÄÄ²Û
Û HKl NWlist files in batch queuesWW‡Û
Û HKr NWremove files from batch queuesWWƒWÛ
Û HKc NWclear batch queuesWWÛ
Û²ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ²Û
ÛW HKq NWquit to file transfer menuWW‡Û
ÛÛÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÛÛ
Z