lnhwfile listing:
‹nwÚÄÄÄÄÄÄÄÄif nhw+ nwthen extended description exists, but not displayed
‹³ÚÄÄÄÄÄÄÄfile flag for fast tagging
Úfilename   ³³    ÚÄÄfile size
³ extension¿³³    ³ Úif nhw- nwthen file is offline
³‰³³³    ³ ³¦Údescription
nhwsbbs200g.zip+nwa  nk851k-nwsynchronet v2.00g multinode bbs software

nhwbatch flagging commands:

nhw[nybnhw]atch                 nwadd file(s) to queue (and nhw[nydnhw]ownload immediatelynw)
nhw[nyvnhw]iew files‹nwview archive listing or contents of file(s)
nhw[nyenhw]xtended infoˆnwdisplay extended information on file(s)
nhw[nytnhw]oggle description    nwtoggle extended/short file description display
nhw[nysnhw]kip directory‡nwskip this directory (during scans)
nhw[nypnhw]reviousnwmove backwards through this directory
nhw[nyqnhw]uit‘nwstop listing files
(
nhwoperator commands:

nhw[nyrnhw]emove files‰nwdelete file(s) from disk and/or database
nhw[nymnhw]ove files‹nwmove file(s) to another directoryn
)
