NY@HOT@N@CLEAR@
0WÚÄÄÄÄÄÄÄÄÄÄÄK¿
W³ HKchat menu N0K³
WÀKÄÄÄÄÄÄÄÄÄÄÄÙ0WÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ÛßW‰Wß0 HWjoin a chat NWßW‰WßÛ
Û YjY NWjoin/initiate multinode chatW…WÛ
Û YpNW join/start private node/node chatW WÛ
Û YcY NWchat with sysop: HK@SYSAVAIL-L####@NW WÛ
Û YtY NWtalk with the guru (ai)WŠWÛ
Û YfY NWfinger (query) remote user/systemW WÛ
Û YrY NWinternet relay chat (irc)WˆWÛ
Û YiY NWinterbbs instant messagingW‡WÛ
Û²ÄÄÄÄÄÄÄÄÄÄÄÄß0 HWtoggles NWßÄÄÄÄÄÄÄÄÄÄÄÄ²Û
Û Yd NWchat availabilityW…Wstate: HK@PAGER-L3@W NWÛ
Û Ya NWnode activity alertsW‚Wstate: HK@ALERTS-L3@NW WÛ
ÛY sY NWsplit-screen chatW…Wstate:W HK@SPLITP-L3@N WÛ
Û²ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ²Û
Û YqY NWquit chat menuW“WÛ
0K W HKanytime: W^uN0Wsers online  H^pN0Wrivate msgH 
Z