NY@HOT@N@CLEAR@
0WÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄK¿
W³ HKelectronic mail menu N0K³
WÀKÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ0WÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ÛßWŠWßÛH0Wsend mailNWÛßWŠWßÛ
Û YsY NWsend mail to a local userWˆWÛ
Û YaY NWsend file attachmentWWÛ
Û YfY NWsend feedback to the sysopW‡WÛ
Û YnY NWsend netmail (fido/qwk/internet)W  WÛ
ÛÛÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÛÛ
ÛßWŠWßH0W read mail NWßWŠWßH0W 
NWÛW YrY NWread mail sent to youWŒH0 
NWÛW YuY NWread your un-read mail onlyW†H0 
NWÛW YkY NWread/kill mail you have sentW…H0 
NWÛÛÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÛH0W 
NWÛ YqY NWquit the e-mail menuWH0 
NWÛÛH0Yanytime: W^uWsers onlineY  W^pWrivate msgW 
Z