nlÄnh‹‹‹‹ € ‹‹  ‹‹ﬁ€ ‹ ‹‹‹‹ ‹‹ ‹‹  ‹‹‹‹‹‹‹ nw‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹
hw0ﬂnw‹‹ h0ﬂÄﬂÄnw‹ h0ﬂÄﬂÄnw‹h0ﬂnw‹h0ﬂnw‹‹‹hﬂ 0ﬂÄﬂÄnw‹ h0ﬂÄﬂnw‹‹ ‹wgj €w0@TIME-L@ @DATE@  wh@BOARDNAME-L19@ 
n  wh0ﬂnw›hﬂ0ﬂ0ﬂ 0ﬂÄﬂÄﬂÅﬂÄﬂnw›h0ﬂÄﬂnw›h0ﬂÄﬂÄﬂÄﬂÄﬂÇﬂÇnw€hw0last onk: n0@LASTDATEON@  hwnode knw0@NODE-L3@ wup w@UPTIME-L8@
nw ﬂﬂ  ﬂ  ﬂ €›ﬂﬂﬂﬂ €›  €€ﬂﬂ  ﬂ €›ﬂﬂﬂ ﬂ   €0hwfirstonk:n0 @SINCE@  hwcallsnw0@STATS.LTODAY-R4@ wofw @TCALLS-L7@
n                                       wﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂ@EOF@