N@CLEAR@Y@HOT@
N0WÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄK¿
W³  HKreading mail menu    N0K³
WÀKÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ0WÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ÛßWW³WWßÛ
ÛY<cr> NWnext msgW„W³W -  previous msgW  WÛ
Û Y[ ]NW search toWƒW³Y{ }Y NWsearch fromW‚WÛ
Û Y< > NWsearch subj  W³ Y/NW  Wsearch textW‚WÛ
Û  YlNW  Wlist msgs    W³W H!NW  reverse listW  WÛ
Û  YtNW  Wnext ten msgsW³W HnNW  Wnext unreadW‚WÛ
Û  Y@MSGREREAD@NW  Wre-read msg  W³W Y@MSGREPLY@NW  Wreply to msg  WÛ
Û  YdNW  Wdelete msgW‚W³ YkNW  delete allWƒWÛ
Û  YfNW  Wforward msg  W³W Y#NW  goW Wto msg num WÛ
ÛÜ YvNW  Wview spamWƒW³W HqNW  quit readingW ÜÛ
ÛÛH0Yanytime: W^uWsers online  W^pWrivate msg 
Z
