NY@HOT@N@CLEAR@
0WÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄK¿
W³ HKmessage scan configuration N0K³
WÀKÄ0Wßßßßßßßßßßßßßßßßßßßßßßßßßßß0KÙ0WÜÜÜÜÜÜÜÜÜ
Û YnY NWareas to scan for new messagesW‚WßÛ
ÛW YsY NWareas to scan for your messagesW‚WÛ
Û Yp NWset new-scan pointersWŒWÛ
Û Yi NWreinitialize new-scan pointersWƒWÛ
Û Yr NWreload new-scan config & pointers WWÛ
Û Yw NWsave new-scan config & pointers   WWÛ
Û²ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ²Û
Û Yq NWquit to main/message menu         WWÛ
ÛÛÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÛÛ
Z
