N@CLS@HW@BBS-C39@
WÚÄNÄÄÄÄÄÄÄÄÄ¿
³H WmessagesW N³
ÀÄÄÄÄÄÄÄÄÄHÄÙ
 W[WnW]ew message scan [W&W]N HKconfig/reset
 [WjW]ump to a message area
 [WrW]ead messages
 [WpW]ost a message
 [WfW]ind text in messages
 [WsW]can for messages to you
 [WeW]mail
NYmain menuNƒHKgetNK HK[WqW]wk
WÚÄNÄÄÄÄÄÄ¿…HK~~~~~~~~~NƒHKget [WiW]nfo
N³H Wgo toW N³‘HKlist [WuW]sers
NÀÄÄÄÄÄÄHÄÙN’HKlog [WoW]ff
W W[WtW]ransfer filesNˆ@SYSONLY@HKsysop [W!W]menuN@SYSONLY@
HK [WgW]eneral text file area
 [WcW]hat section
 [WxW]ternal programs
 [WdW]isplay/change your configuration
Z