NY@HOT@N@CLEAR@
0WÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄK¿
W³ HKmain section information menu N0K³
WÀKÄ0Wßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß0KÙ0WÜÜÜÜÜÜ
ÛW Yy NWyour statisticsWWW‘WßÛ
Û YiY NWsystem informationWWWWÛ
ÛW YvY NWsynchronet version informationWWWƒWÛ
Û YsY NWinformation on current sub-boardWW  WÛ
Û²ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ²Û
Û Yq NWquit to main menuWWWWÛ
ÛÛÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÛÛ
Z