@INCLUDE:%zmenu/head.msg@hw@HOT@n
 wşhş wread/post messages…nwşhş wmessage area selection   nwşhş welectronic mail
wÚnwÄÄ¿–hÚnwÄÄ¿—hÚnwÄÄ¿
³ ynnw³ wnew message scan…w³ yjnw³ wjump to new msg area   w³ yenw³ wread/send e-mail
w³ yrnw³ wread message prompt   wÀÄÄÙ   hw* nlist sub-boards    wÀÄÄÙ
³ ylnw³ wlist/view messages          hw/* nlist groupsˆwşhş wother commands
nw³ yvnw³ wview/vote-in polls      hw{ }  w# nselect sub-board   hwÚnwÄÄ¿
³ yqnw³ wqwk packet transfer„hw[ ] w/# nselect group†w³ ydnw³ wdefault user config
w³ ypnw³ wpost msg hw/pnoll hw/mneme                              w³ hw&nw³ wmessage scan config
w³ yanw³ wpost auto-message…wşhş wgo to’nw³ yunw³ wuser lists
wÀÄÄÙ–hÚnwÄÄ¿—³ yinw³ winformation
 wşhş wmessage searchˆnw³ ytnw³ wfile transfer section  w³hw/anw³ wchange your avatar
hwÚnwÄÄ¿–³ ygnw³ wtext file section…w³hw/lnw³ wnode activity
w³ yfnw³ wfind text in messages w³ ycnw³ wchat sectionŠw³hw^knw³ wctrl-key menu
w³ ysnw³ wscan for msgs to you  w³ yxnw³ wexternal programs…w³ yonw³ wlogoff bbs (or hw/on)
wÀÄÄÙ–ÀÄÄÙ—ÀÄÄÙ @SYSONLY@nhw!n sysop menu@SYSONLY@
@HOT:OFF@@INCLUDE:%zmenu/tail.msg@