NY@HOT@
N0WÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄK¿0
0W³ HKmultinode chat menu N0K³0
0WÀKÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ0WÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜK
WÛßYN¢WßÛK
WÛY /w NWwhisper to another userW‰WÛK
WÛY /l NWlist all node activityWŠWÛK
WÛY /* NWlist chat channelsWWÛK
WÛY /# NWchange chat channel number†WÛK
WÛ Y/e NWtoggle echo statusWWWÛK
WÛY /a NWtoggle action commandsŠWÛK
WÛY /c NWlist action commandsŒWÛK
WÛY /q NWquit multinode chatWÛK
WÛÜWW¢WÜÛK
0  HKanytime: W^uN0Wsers online  H^pN0Wrivate msg 0K
Z
