NY@HOT@N@CLEAR@
0WÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄK¿
W³  HKqwk offline reader menu  N0K³
WÀKÄ0Wßßßßßßßßßßßßßßßßßßßßßßßßßß0KÙ0WÜÜÜÜÜÜÜ
Û YcY NWchange packet configurationW‚WßÛ
Û YsY NWselectW Wmessage areas to scanW‚WÛ
Û YpY NWmodify new-message pointersWƒWÛ
Û YuY NWupload rep reply packetW‡WÛ
Û YdY NWdownload qwk message packetWƒWÛ
Û²ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ²Û
Û YqY NWquit back to main menuWˆWÛ
ÛÛÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÛÛ
Z