NW@CLEAR@
0WÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄK¿
W³  HKsub-board operator menu  N0K³
WÀKÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ0WÜÜÜÜÜÜÜ
ÛW¡WÛ
Û HKa NWadd comment to last messageƒWÛ
Û HKc NWchange message attributesW…WÛ
Û HKd NWdelete messages (in a range)‚WÛ
Û HKh NWview message headerW‹WÛ
Û HKm NWmove message to another subƒWÛ
Û HKs NWsave message to text fileW…WÛ
Û HKu NWedit author's user accountW„WÛ
Û HKp NWpurge author's user accountƒWÛ
Û HKv NWvalidate previous messageW…WÛ
Û HKt NWtwit-list author               WWÛ
ÛÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÛ
Û HKq NWquit back to reading promptƒWÛ
ÛÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÛ
Z