N@CLS@HW@BBS-C39@
WÚÄNÄÄÄÄÄÄÄÄÄ¿
³H WlistingsW N³
ÀÄÄÄÄÄÄÄÄÄHÄÙ
 W[WnW]ew files scan [W&W]N HKconfig/reset
 [WlW]ist files in current directory
W W[WjW]ump to a fileN HKarea
 [WeW]xtended file information
 [WfW]ind text in descriptions
 [WsW]earch for filenames
 [WvW]iew file contents
N HK[WrW]emove file
NYfile menu
WÚÄNÄÄÄÄÄÄÄÄÄ¿‚HK~~~~~~~~~NƒHKget [WiW]nfo
N³H WtransferW N³HKlog [WoW]ff
NÀÄÄÄÄÄÄÄÄÄHÄÙNHKorN HK[WqW]uit
W W[WdW]ownload file(s)N†@SYSONLY@HKsysop [W!W]menuN@SYSONLY@
 HK[WuW]pload file(s)W  W[WzW]N HKto sysop
 [WbW]atch transfer menu
 [WtW]emporary directory
Z