@INCLUDE:%zmenu/head.msg@hk@HOT@n
0w0ЫЫЫЫЫ0 hwlist/flag files nwЫЫЫЫЫЫЫ0 hwfile area selection nwЫЫЫЫЫЫЫЫЫ0 hwfile search  nwЫЫЫЫЫЫ
ЫЫЫЫ
Ы  hkl nwlist files in dir    wЫ hkj nwjump to new file area wЫ  hkf nwfind text in descrip wЫ
Ы  hkn nwnew file scan        wЫДДДДДДДДДДДДДДДДДДДДДДДДДЫ  hks nwsearch for filename  wЫ
Ы  hke nwextended file info   wЫ…hk* nwlist directories wЫЫ
ЫЫ„hk/* nwlist libraries   wЫЫЫЫЫЫ0 hwother commands nwЫЫЫЫЫ
ЫЫЫЫЫ0 hwupload/download nwЫЫЫЫЫ hk{ }  w# nwselect directory wЫ
 Ы hk[ ] w/# nwselect library   wЫ  hk& nwfile scan config
   hkd nwdownload file‡wЫЫ  hkr nwremove/edit file
   hku nwupload file‰wЫЫЫЫЫЫЫЫЫЫ0 hwgo to nwЫЫЫЫЫЫЫЫЫЫ  hki nwinformation
  hk/d nwdownload from user   wЫЫ  hkv nwview file contents
  hk/u nwupload to user†wЫ hkq nwmain/message section  wЫ hk/l nwnode activity
   hkz nwupload to sysop…wЫ hkc nwchat section‰wЫ hk^k nwctrl-key menu
   hkb nwbatch/bi-dir xfers   wЫ hkt nwtemp dir/archive cmds wЫ  hko nwlogoff bbs (or hk/onw)
w ЫЫ  @SYSONLY@hk!nw sysop menu@SYSONLY@
@HOT:OFF@@INCLUDE:%zmenu/tail.msg@