NHK@HOT@N@CLEAR@
0WÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄK¿
W³ HKfile section information menu N0K³
WÀKÄ0Wßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß0KÙßß0WÜÜÜÜ
ÛW HKy NWyour file transfer statisticsWWƒßÛ
Û HKt NWfile transfer policyWWWWÛ
ÛW HKd NWinformation on current directoryWW  WÛ
Û HKu NWusers with access to current dirWW  WÛ
Û²ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ²Û
Û HKq NWquit to file transfer menuW‡WÛ
ÛÛÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÛÛ
Z