NHK@HOT@N@CLEAR@
0WÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄK¿
W³ HKfile scan configuration N0K³
WÀKÄ0Wßßßßßßßßßßßßßßßßßßßßßßßß0KÙ0WÜÜÜÜÜÜÜÜÜÜÜÜ
Û HKp NWset new-scan pointerWŒWßÛ
ÛW HKbNW toggle batch file flagging on/offW WÛ
Û HKe NWtoggle extended descriptionsW…WÛ
Û²ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ²Û
Û HKq NWquit to file transfer menuW‡WÛ
ÛÛÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÛÛ
Z